# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.test.demo
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger                # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true
# Swagger
#springdoc:
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  api-docs:
#    groups:
#      enabled: true
#  swagger-ui:
#    operations-sorter: alpha # alpha(알파벳 오름차순), method(HTTP메소드순)
#    tags-sorter: alpha # 태그 정렬 기준
#    path: /swagger # html 문서 접속 경로
#    disable-swagger-default-url: true
#    display-query-params-without-oauth2: true
#    doc-expansion: none # tag, operation 펼치는 방식
#  paths-to-match:
#    - /**