#DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ideacdb.ce84mlt0kgjd.ap-northeast-2.rds.amazonaws.com:3306/ideacdb?useSSL=false
    username: admin
    password: '!ideacampus10'
  jpa:
    hibernate:
      ddl-auto: update  # 프로덕션 환경에서는 'none' 또는 'validate'로 변경
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    # 로컬 : "h2"  ||  RDS : "rds"로 사용
    active: [ "swagger","mail" ]

# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8080



