spring :
  mail :
    host : smtp.gmail.com
    port : 587
    username : ideac2587@gmail.com
    password : snve mylt ikyk alpy
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true