#DB 설정
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ideacdb.ce84mlt0kgjd.ap-northeast-2.rds.amazonaws.com:3306/ideacdb?useSSL=false
    username: admin
    password: '!ideacampus10'
  jpa:
    hibernate:
      ddl-auto: update  # 프로덕션 환경에서는 'none' 또는 'validate'로 변경
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 오류 처리
server:
  error:
    include-exception: true
    include-stacktrace: always

  #port 설정
  port: 8081

# 파일 업로드 경로(배포 후 원격 서버로 수정)
upload:
  path: C:\\Users\\LG\\Desktop\\Study\\